wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
batch_size:
  desc: null
  value: 5
channels:
  desc: null
  value:
  - NDVI
  - NDBI
  - NDWI
classes:
  desc: null
  value:
  - LSTN
comparison_loss_factor:
  desc: null
  value: 1.2
comparison_loss_fn:
  desc: null
  value: mse_loss
data_dir:
  desc: null
  value: ../data_source/LONDON_DATASET
dis_dropout:
  desc: null
  value: 0.4
gen_dropout:
  desc: null
  value: 0.4
loss_parameters:
  desc: null
  value: null
lr:
  desc: null
  value: 0.0001
num_epochs:
  desc: null
  value: 20
random_state:
  desc: null
  value: null
save_rate:
  desc: null
  value: 1
task:
  desc: null
  value: reg
test_metric:
  desc: null
  value: mse_loss
test_parameters:
  desc: null
  value: null
test_size:
  desc: null
  value: 0.2
train_size:
  desc: null
  value: null
wandb:
  desc: null
  value: 1

WARNING:root:Found 3088 images in total
WARNING:root:Found 224 groups in root directory
179 training instances, 45 testing instances
Starting training for 20 epochs of 36 training steps and 9 evaluation steps
/scratch/hw501/anaconda3/envs/satellite/lib/python3.8/site-packages/torch/nn/modules/loss.py:432: UserWarning: Using a target size (torch.Size([4, 256, 256, 1])) that is different to the input size (torch.Size([4, 1, 256, 256])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
Epoch: 0   Step: 0   Batch Loss: 1.0596   Epoch Loss: 1.0596   Epoch ETA: 0.0 m  35 sTraceback (most recent call last):
  File "train_cGAN.py", line 121, in <module>
    train_cGAN(config)
  File "/scratches/mario/hw501/satellite-cGAN/cGAN.py", line 499, in train_cGAN
    epoch_loss = train_cGAN_epoch(
  File "/scratches/mario/hw501/satellite-cGAN/cGAN.py", line 389, in train_cGAN_epoch
    wandb.log(
AttributeError: 'int' object has no attribute 'log'
